import { Container } from "semantic-ui-react";
import Head from "next/head";

import Header from "./Header";

function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title || "CrowdCoin"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <main>{children}</main>
      </Container>
    </>
  );
}

export default Layout;
