import { useEffect } from "react";
import Head from "next/head";
import factory from "../ethereum/factory";

export default function Home() {
  useEffect(() => {
    const getCampaigns = async () => {
      const campaigns = await factory.methods.getDeployedCampaigns().call();
      console.log(campaigns);
    };
    getCampaigns();
  }, []);

  return (
    <div>
      <Head>
        <title>Crowdcoin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>This is the campaign list page</h1>
      </main>
    </div>
  );
}
